/**
 * TMUX Session Sweeper — orphan cleanup for the lifecycle-manager.
 *
 * Periodically audits tmux sessions against the AO session DB and kills
 * sessions that are:
 * 1. AO-managed tmux sessions whose names match the `{12-hex-hash}-{prefix}-{NNN}`
 *    pattern accepted by `parseTmuxName` (where `prefix` is one of the
 *    configured `aoSessionPrefixes`; defaults to ao,jc,wa,cc,ra,wc).
 *    Note: bare tmux sessions named like `ao-42` do not match this pattern
 *    and are not considered AO-managed sessions for sweeping.
 * 2. Absent from the AO session DB (no metadata file)
 * 3. Idle beyond the configured threshold (default: 30 minutes)
 *
 * This prevents gradual tmux accumulation that would eventually block the
 * spawn gate (>15 sessions). Orphans arise from:
 * - Lifecycle-manager restarts mid-session
 * - Sessions killed outside AO's control
 * - Corrupted/deleted metadata files
 * - Sessions spawned by other AO installations on the same machine
 *
 * Invoked periodically by the lifecycle-manager; in the default integration
 * this sweep is throttled to roughly every 5 minutes, not every 30s.
 */

import { listSessions, killSession, type TmuxSessionInfo } from "./tmux.js";
import { parseTmuxName } from "./paths.js";
import type { SessionManager } from "./types.js";

// =============================================================================
// Types
// =============================================================================

/** Default AO session name prefixes used when none are provided via config. */
export const DEFAULT_AO_SESSION_PREFIXES = new Set(["ao", "jc", "wa", "cc", "ra", "wc"]);

export interface TmuxSweeperConfig {
  /**
   * Milliseconds a session must be idle before it is considered killable.
   * Default: 30 minutes (1_800_000 ms)
   */
  orphanIdleThresholdMs: number;
  /**
   * Maximum orphan tmux sessions to kill per sweep invocation (counting both
   * successful kills and non-benign errors against the cap).
   * Default: 10
   */
  maxKillsPerSweep: number;
  /**
   * Session name prefixes that identify AO-managed tmux sessions.
   * Used with `parseTmuxName` to filter tmux sessions for sweeping.
   * Default: DEFAULT_AO_SESSION_PREFIXES
   */
  aoSessionPrefixes: Set<string>;
  /**
   * If true, log what would be killed but do not actually kill.
   * Default: false
   */
  dryRun?: boolean;
  /**
   * Optional logger for sweep events.
   */
  log?: (msg: string) => void;
}

export interface SweptOrphan {
  tmuxName: string;
  aoSessionId: string;
  created: string;
  idleMs: number;
  reason: string;
}

export interface SkippedOrphan {
  tmuxName: string;
  reason: string;
}

export interface SweeperError {
  tmuxName: string;
  error: string;
}

export interface TmuxSweepResult {
  killed: SweptOrphan[];
  skipped: SkippedOrphan[];
  errors: SweeperError[];
  dryRun: boolean;
  scanned: number;
}

export interface TmuxSweeperDeps {
  sessionManager: SessionManager;
  /** Override current time (testing only) */
  now?: Date;
}

// =============================================================================
// Default config
// =============================================================================

export const DEFAULT_TMUX_SWEEPER_CONFIG: TmuxSweeperConfig = {
  orphanIdleThresholdMs: 1_800_000, // 30 minutes
  maxKillsPerSweep: 10,
  aoSessionPrefixes: DEFAULT_AO_SESSION_PREFIXES,
};

// =============================================================================
// Core sweeper logic
// =============================================================================

/**
 * Result of parsing a tmux session name as an AO session.
 */
interface ParsedAoSession {
  /** The full tmux session name, e.g. "aabbccddeeff-ao-42" */
  tmuxName: string;
  hash: string;
  prefix: string;
  num: number;
  /** The AO session ID without hash, e.g. "ao-42" */
  sessionId: string;
}

/**
 * Try to parse a tmux session name as an AO-managed session.
 * Returns null if the name doesn't match the expected `{hash}-{prefix}-{num}` format
 * or if the prefix is not in `allowedPrefixes`.
 *
 * AO tmux session names are generated by `generateTmuxName` in paths.ts:
 *   {12-hex-hash}-{prefix}-{num}
 * Example: "aabbccddeeff-ao-42", "deadbeef123456-jc-7"
 */
function tryParseAoSession(
  session: TmuxSessionInfo,
  allowedPrefixes: Set<string>,
): ParsedAoSession | null {
  const parsed = parseTmuxName(session.name);
  if (!parsed) return null;
  if (!allowedPrefixes.has(parsed.prefix)) return null;
  return {
    tmuxName: session.name,
    hash: parsed.hash,
    prefix: parsed.prefix,
    num: parsed.num,
    sessionId: `${parsed.prefix}-${parsed.num}`,
  };
}

/**
 * Compute how long a tmux session has existed (used as idle proxy when
 * last-activity is unavailable for detached sessions).
 *
 * AO tmux sessions are created detached, so the session creation time
 * is the best available idle proxy. For genuinely orphaned sessions
 * (process crashed, metadata deleted) the session will be detached and
 * old; active sessions will have recent creation times.
 *
 * Parses tmux's `session_created_string` format (e.g. "Mon Mar 23 12:00:00 2025")
 * and returns milliseconds since creation.
 *
 * Safe-by-default: if the creation time cannot be parsed, we return 0 ms
 * (not-maximum) to avoid accidentally sweeping active sessions due to
 * locale/format mismatches.
 */
function computeIdleMs(session: TmuxSessionInfo, now: Date): number {
  try {
    // tmux format: "Mon Mar 23 12:00:00 2025"
    const createdDate = new Date(session.created);
    if (isNaN(createdDate.getTime())) {
      // Fallback: treat unparseable dates as zero idle (conservative/safe)
      return 0;
    }
    return now.getTime() - createdDate.getTime();
  } catch {
    // If parsing fails entirely, be conservative and treat as zero idle
    return 0;
  }
}

/**
 * Audit all tmux sessions and kill orphans not tracked in the AO DB.
 *
 * @param config   - Sweeper configuration (threshold, prefixes, dryRun, etc.)
 * @param deps     - Dependency injection (sessionManager, optional now)
 * @returns Result describing what was killed, skipped, or errored
 */
export async function sweepOrphanTmuxSessions(
  config: TmuxSweeperConfig,
  deps: TmuxSweeperDeps,
): Promise<TmuxSweepResult> {
  const now = deps.now ?? new Date();
  const dryRun = config.dryRun ?? false;
  const logFn = config.log ?? ((_msg: string) => {});
  const allowedPrefixes = config.aoSessionPrefixes ?? DEFAULT_AO_SESSION_PREFIXES;

  const allTmuxSessions = await listSessions();
  const scanned = allTmuxSessions.length;

  // Get all active AO session IDs from the DB.
  // Compare using the full tmux name when available, falling back to session.id
  // so we don't incorrectly match a local "ao-42" against a foreign "xxyyzz-ao-42".
  const aoSessions = await deps.sessionManager.list();
  const aoTmuxNames = new Set(
    aoSessions.flatMap((s) => (s.tmuxName ? [s.tmuxName] : [])),
  );
  // Legacy sessions (created before tmuxName was added to metadata) have no
  // tmuxName in the DB. Track their session IDs so we can still match them
  // against scanned sessions and avoid incorrectly sweeping them.
  const aoLegacySessionIds = new Set(
    aoSessions.flatMap((s) => (!s.tmuxName ? [s.id] : [])),
  );

  const killed: SweptOrphan[] = [];
  const skipped: SkippedOrphan[] = [];
  const errors: SweeperError[] = [];

  for (const session of allTmuxSessions) {
    // Skip attached sessions — someone is actively using this tmux pane
    if (session.attached) {
      skipped.push({ tmuxName: session.name, reason: "session is attached" });
      continue;
    }

    // Try to parse as AO-managed session using the configured prefix set
    const parsed = tryParseAoSession(session, allowedPrefixes);
    if (!parsed) {
      // Not an AO-named session (e.g., user's manual tmux sessions)
      continue;
    }

    // Skip sessions tracked in the AO DB — they are legitimate active sessions.
    // Prefer tmuxName (full hash-prefixed name) for modern sessions.
    // For legacy sessions (no tmuxName in DB), fall back to sessionId.
    if (aoTmuxNames.has(parsed.tmuxName)) {
      skipped.push({ tmuxName: session.name, reason: "tracked in AO DB" });
      continue;
    }
    if (aoLegacySessionIds.has(parsed.sessionId)) {
      skipped.push({ tmuxName: session.name, reason: "tracked in AO DB (legacy — no tmuxName in metadata)" });
      continue;
    }

    // Session is not in the AO DB — check idle time
    const idleMs = computeIdleMs(session, now);

    if (idleMs < config.orphanIdleThresholdMs) {
      skipped.push({
        tmuxName: session.name,
        reason: `not yet idle (${Math.round(idleMs / 60_000)}min < ${Math.round(config.orphanIdleThresholdMs / 60_000)}min threshold)`,
      });
      continue;
    }

    // Orphan candidate: AO-named, not in AO DB, past idle threshold, not attached
    const reason = `no AO DB record, idle ${Math.round(idleMs / 60_000)}min`;

    // Count both successful kills and non-benign errors against the cap
    if (killed.length + errors.length >= config.maxKillsPerSweep) {
      skipped.push({ tmuxName: session.name, reason: "max kills per sweep reached" });
      continue;
    }

    logFn(`[tmux-sweeper] ${dryRun ? "[DRYRUN] " : ""}killing orphan tmux session: ${session.name} (${reason})`);

    if (!dryRun) {
      try {
        await killSession(session.name);
        killed.push({ tmuxName: session.name, aoSessionId: parsed.sessionId, created: session.created, idleMs, reason });
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        // "no server" / "session not found" means it vanished between list and kill — not an error
        if (/session not found|no server/i.test(msg)) {
          logFn(`[tmux-sweeper] session already gone: ${session.name}`);
        } else {
          errors.push({ tmuxName: session.name, error: msg });
        }
      }
    } else {
      killed.push({ tmuxName: session.name, aoSessionId: parsed.sessionId, created: session.created, idleMs, reason });
    }
  }

  return { killed, skipped, errors, dryRun, scanned };
}
